nginx:
    build: nginx/
    ports:
      - "80:80"
    links:
      - consul:consul
    restart: always
hello:
    build: hello/
    links:
      - consul:consul
goodbye:
    build: goodbye/
    links:
      - consul:consul
world:
    build: world/
    links:
      - consul:consul
consul:
    image: consul:latest
    restart: always
    ports:
      - "8500:8500"
